---

- name: add directory to fstab
  template:
    src: exports.j2
    dest: /etc/exports
  notify: restart nfs service


- name: enable exportfs
  shell: mount -t nfs 3.3.3.3:/backup/nfs_1/ /backup && mount -t nfs 3.3.3.3:/backup/nfs_2/ /backup
