---
zabbix_server_version: 5.0
zabbix_server_version_minor: "*"
zabbix_version: "{{ zabbix_server_version }}"
zabbix_repo_yum_schema: https
zabbix_repo: zabbix
zabbix_arch: x86_64
zabbix_repo_yum:
  - name: zabbix
    baseurl: "{{ zabbix_repo_yum_schema }}://repo.zabbix.com/zabbix/{{ zabbix_version | regex_search('^[0-9]+.[0-9]+') }}/rhel/7/{{ zabbix_arch }}/zabbix-release-5.0-1.el7.noarch.rpm"
    state: present
    mode: '0644'
    dest: /tmp
    description: Zabbix Official Repository - $basearch

