---
zabbix_server_version: 5.0
zabbix_server_version_minor: "*"
zabbix_version: "{{ zabbix_server_version }}"
zabbix_repo_yum_schema: https
zabbix_repo: zabbix
zabbix_mysql_directory: /usr/share/doc/zabbix-server-mysql-4.2.8
ansible_distribution_major_version: 5
zabbix_repo_yum_gpgcheck: 0
zabbix_arch: x86_64
zabbix_server_username: zabbix
zabbix_server_groupname: zabbix
zabbix_rpm_file: zabbix-release-5.0-1.el5.noarch.rpm
zabbix_repo_yum:
  - name: zabbix
    description: Zabbix Official Repository - $basearch
    baseurl: https://repo.zabbix.com/zabbix/5.0/rhel/5/x86_64/zabbix-release-5.0-1.el5.noarch.rpm
    gpgcheck: "{{ zabbix_repo_yum_gpgcheck }}"
    mode: '0755'
    directory: /home/it/zabbix
    state: present
    owner: root
    group: root

zabbix_packages:
  - zabbix-server-mysql
  - zabbix-agent
  - zabbix-web-mysql
  - zabbix-get

zabbix:
  db_name: zabbix
  db_user: zabbix
  db_password: zabbixpassword
  agent_packages:
    - zabbix-agent

