---

- name: copy config file
  template:
    src: unifi.service.j2
    dest: "{{ unifi.unifi }}/unifi.service"
  tags: unifi

- name: configure mongodb
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
  tags: mongodb

- name: start unifi and mongodb service
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - unifi
    - mongod

