---

-  name: copy conf file
   template:
     src: zabbix_agentd.conf.j2
     dest: "{{ item.directory }}/zabbix_agentd.conf"
     owner: "{{ item.owner }}"
     group: "{{ item.owner }}"
     mode: "{{ item.mode }}"
  loop: "{{ zabbix_repo_yum }}"

- name: start zabiix agent
  service:
    name: zabbix-agent
    state: started
    enabled: yes

