---
- name: copy 90 routing sysctl and add to sysctl daemon
  block:
    - name: copy 90 routing sysctl
      template:
        src: 90-routing-sysctl.conf.j2
        dest: /etc/sysctl.d/90-routing-sysctl.conf

    - name: add to sysctl daemon
      command: sysctl -p /etc/sysctl.d/90-routing-sysctl.conf

- name: copy daemons frr
  template:
    src: daemons.j2
    dest: /etc/frr/daemons
    notify: restart frr service