---

- name: Install libyang and frr
  block:
    - name: install libyang
      yum:
        name: /home/it/frr/libyang-0.16.111-0.x86_64.rpm
        state: present

    - name: install frr
      yum:
        name: /home/it/frr/frr-7.0-01.el7.webinar_2.x86_64.rpm
        state: present

    - name: start frr
      service:
        name: frr
        state: started
        enabled: yes




#  update_cache: yes
