---

- name: copying config files on R1
  block:
    - name: copy on R1
      template:
        src: "{{ team.team0_r1 }}"
        dest: "{{ team.dir }}/ifcfg-team0"

    - name: copy slave interface ens37
      template:
        src: "{{ team.ens37 }}"
        dest: "{{ team.dir }}/ifcfg-ens37"

    - name: copy slave interface ens38
      template:
        src: "{{ team.ens38 }}"
        dest: "{{ team.dir }}/ifcfg-ens38"

  when: " 'R1' in inventory_hostname"

- name: copying config files on R2
  block:
    - name: copy on R2
      template:
        src: "{{ team.team0_r2 }}"
        dest: "{{ team.dir }}/ifcfg-team0"

    - name: copy slave interface ens37
      template:
        src: "{{ team.ens37 }}"
        dest: "{{ team.dir }}/ifcfg-ens37"

    - name: copy slave interface ens38
      template:
        src: "{{ team.ens38 }}"
        dest: "{{ team.dir }}/ifcfg-ens38"

  when: " 'R2' in inventory_hostname"

  notify: restart network service



