---

- name: 'INSTALL | install firewalld'
  import_tasks: install.yml

- name: 'PREREQ | prepare to install firewall'
  import_tasks: prereq.yml


- name: 'CONFIG | configure firewall'
  import_tasks: config.yml


