---

-  name: copy conf file
   template:
     src: zabbix_server.conf.j2
     dest: /etc/zabbix_server.conf
     owner: root

- name: start zabiix server
  service:
    name: zabbix-server
    state: started
#    enabled: yes