---

- name: Install and start zabbix server
  block:
    - name: install zabbix-release
      yum:
        name: "{{ item.directory }}/{{ zabbix_rpm_file }}"
        state: "{{ item.state }}"
        update_cache: yes
      loop: "{{ zabbix_repo_yum }}"

    - name: install zabbix packages
      yum:
        name: "{{ item.server_packages }}"
        state: present
        update_cache: yes
      loop: "{{ zabbix }}""


