---

- name: create directory and dowload zabbix
  block:
    - name: mkdir for zabbix package
      file:
        path: "{{ item.directory }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"

    - name: dowload zabbix-release
      get_url:
        url: "{{ item.baseurl }}"
        dest: "{{ item.directory }}"

  loop: "{{ zabbix_repo_yum }}"